HW4 is done
AnnaBlok/GOtus pull request #6
Opened 2023-11-20 13:35 UTC by AnnaBlok

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-11-20 18:38 UTC, vladislavmass requested changes
Хорошее начало. Радует что решили сделать код потокобезопасным и это получилось. Рекомендую пересмотреть реализцию методов Push двусвязного списка, так как они реализованы некорректно

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/go.mod
> +module github.com/AnnaBlok/hw04_lru_cache
Неверное имя модуля

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if i == l.front {
Если в листе всего 1 элемент, то в данном случае l.front перезапишется. а l.back так и будет указывать на  удаленный элемент

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 2 && l.front == nil {
Несовсем понятно причем тут ситуация когда длина списка равна 2

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 2 && l.back == nil {
Несовсем понятно причем тут ситуация когда длина списка равна 2

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	items    map[Key]cacheItem
В большом и нагруженом кэше использование значений будет не самым оптимальным вариантом из за операций копирования, поэтому тут лучше использовать все таки указатель

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +		if c.queue.Len() > c.capacity {
Подразумевается что размер очереди не может привышать капасити, а это условие сработает только если мы его привысели

2023-11-20 18:38 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	c.items = make(map[Key]cacheItem, c.capacity)
queue тоже надо очищать

2023-11-21 06:39 UTC, AnnaBlok commented on hw04_lru_cache/go.mod
> +module github.com/AnnaBlok/hw04_lru_cache
\+

2023-11-21 06:49 UTC, AnnaBlok commented on hw04_lru_cache/list.go
> +	if i == l.front {
разве? у меня есть тест "remove the last item", который проверяет данный кейс (+добавила туда сейчас тест с PushBack()). в методе Remove() данный случай обрабатывается первыми условиями: l.back это i.Next

2023-11-21 06:53 UTC, AnnaBlok commented on hw04_lru_cache/list.go
> +	if l.len == 2 && l.front == nil {
я подразумевала тут то, что происходит в тесте "only front/back push" - если элементов два, а оба были добавлены через PushBack(), то пора заполнить l.front. почему не написала `l.len > 1` - т.к. в таком случае какой элемент будет l.front уже неочевидно, нужно делать перебор. да и зачем на каждой длине > 1 проверять условие, если я могу закрыть этот кейс на длине 2

2023-11-21 06:53 UTC, AnnaBlok commented on hw04_lru_cache/list.go
> +	if l.len == 2 && l.back == nil {
выше написала

2023-11-21 06:58 UTC, AnnaBlok commented on hw04_lru_cache/cache.go
> +	items    map[Key]cacheItem
спасибо, поправила

2023-11-21 07:00 UTC, AnnaBlok commented on hw04_lru_cache/cache.go
> +		if c.queue.Len() > c.capacity {
изменила порядок. теперь если длина == капасити, то сначала удаляется последний элемент, а потом пушится новый

2023-11-21 07:06 UTC, AnnaBlok commented on hw04_lru_cache/cache.go
> +	c.items = make(map[Key]cacheItem, c.capacity)
спасибо, поправила. добавила тесты для метода Clear()

2023-11-21 15:55 UTC, AnnaBlok commented on hw04_lru_cache/list.go
> +	if i == l.front {
подкорректировала условие, теперь l.front и l.back не взаимоисключающие. добавлено для обработки изменений в Push: теперь при добавлении первого элемента он назначается как front и как back

2023-11-21 16:03 UTC, AnnaBlok commented on hw04_lru_cache/list.go
> +	if l.len == 2 && l.front == nil {
убрала это условие. теперь if l.len == 1

2023-11-22 06:11 UTC, vladislavmass approved these changes
Хорошая работа. Принято.-1 бал за странные имена переменных `cItem,lItem` и наличие излишних условий

2023-11-22 06:11 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 1 {
А разве возможна ситуация когда l.front=nil но при этом мы добовляем не 1 элемент?

2023-11-22 06:33 UTC, merged